language: csharp
solution: istio-tracing-aspnetcore.sln
mono: none
dotnet: 2.2
os:
  - linux
dist: xenial

script:
  - dotnet build istio-tracing-aspnetcore.sln -c Release
  - dotnet test -c Release --no-build istio-tracing-aspnetcore.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - echo "TRAVIS_TAG=$TRAVIS_TAG" 
  - VERSION=`echo $TRAVIS_TAG | grep -oP '(?<=v).*'`
  - echo $VERSION
  - dotnet pack -c Release /p:Version=$VERSION
deploy:
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-999].[0-999].[0-999].*$"
  provider: script
  script: dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY